2023-12-09 18:26:46,408 [ERROR] Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Kernel.poll_control_queue() running at /home/dliu/miniconda3/envs/py38/lib/python3.8/site-packages/ipykernel/kernelbase.py:291> wait_for=<Future finished result=<Future at 0x...state=pending>> cb=[_chain_future.<locals>._call_set_state() at /home/dliu/miniconda3/envs/py38/lib/python3.8/asyncio/futures.py:367]>
